services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    user: 568:568
    ports:
      - 7474:7474
    env_file:
      - ../stack.env
    environment:
      AUTOBRR__HOST: 0.0.0.0
      AUTOBRR__SESSION_SECRET: "${AUTOBRR_SESSION_SECRET}"
      AUTOBRR__DATABASE_TYPE: true
      AUTOBRR__POSTGRES_HOST: autobrr-postgres
      AUTOBRR__POSTGRES_DATABASE: "${AUTOBRR_DB_NAME}"
      AUTOBRR__POSTGRES_USER: "${AUTOBRR_DB_USER}"
      AUTOBRR__POSTGRES_PASS: "${AUTOBRR_DB_PASSWORD}"
      AUTOBRR__OIDC_ENABLED: true
      AUTOBRR__OIDC_DISABLE_BUILT_IN_LOGIN: true
      AUTOBRR__OIDC_ISSUER: "${AUTOBRR_OIDC_ISSUER}"
      AUTOBRR__OIDC_CLIENT_ID: "${AUTOBRR_OIDC_CLIENT_ID}"
      AUTOBRR__OIDC_CLIENT_SECRET: "${AUTOBRR_OIDC_CLIENT_SECRET}"
      AUTOBRR__OIDC_REDIRECT_URL: "${AUTOBRR_OIDC_REDIRECT_URL}"
      AUTOBRR__METRICS_ENABLED: true
      AUTOBRR__METRICS_HOST: 0.0.0.0
      AUTOBRR__METRICS_PORT: 7575
    deploy:
      resources:
        limits:
          memory: 500M
    volumes:
      - "${AUTOBRR_MOUNT_PATH}/config:/config"
    labels:
      prometheus.io/scrape: true
      prometheus.io/path: /metrics
      prometheus.io/port: 7575
      prometheus.io/scheme: http

      traefik.enable: true
      traefik.http.routers.autobrr.rule: Host(`autobrr.starsystem.dev`)
      traefik.http.routers.autobrr.entrypoints: websecure
      traefik.http.services.autobrr.loadbalancer.server.port: 7474
    restart: unless-stopped