services:
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    user: 568:568
    ports:
      - 8686:8686
    env_file:
      - ../stack.env
    environment:
      PUID: 568
      PGID: 568
    volumes:
      - "${LIDARR_MOUNT_PATH}/config:/config"
      - "${MEDIA_MOUNT_PATH}/music:/music"
      - "${MEDIA_MOUNT_PATH}/downloads:/downloads"
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped