services:
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    user: 568:568
    ports:
      - 9696:9696
    env_file:
      - ../stack.env
    environment:
      PUID: 568
      PGID: 568
    volumes:
      - "${PROWLARR_MOUNT_PATH}/config:/config"
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped