services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    user: 568:568
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8080:8080
    env_file:
      - ../stack.env
    environment:
      PUID: 568
      PGID: 568
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    deploy:
      resources:
        limits:
          memory: 2G
    volumes:
      - "${QBITTORRENT_MOUNT_PATH}/config:/config"
      - "${MEDIA_MOUNT_PATH}/downloads:/downloads"
    restart: unless-stopped