services:
  recyclarr:
    container_name: recyclarr
    image: recyclarr/recyclarr:latest
    user: 568:568
    read_only: true
    tmpfs: /tmp
    security_opt:
      - no-new-privileges:true
    env_file:
      - ../stack.env
    volumes:
      - "${RECYCLARR_MOUNT_PATH}/config:/config"
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped