services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    user: 568:568
    ports:
      - 8989:8989
    env_file:
      - ../stack.env
    environment:
      PUID: 568
      PGID: 568
    volumes:
      - "${SONARR_MOUNT_PATH}/config:/config"
      - "${MEDIA_MOUNT_PATH}/shows:/tv"
      - "${MEDIA_MOUNT_PATH}/downloads:/downloads"
    deploy:
      resources:
        limits:
          memory: 500M
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.starsystem.dev`)
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
    restart: unless-stopped