volumes:
  tdarr-cache:

services:
  tdarr:
    container_name: tdarr
    image: haveagitgat/tdarr:latest
    ports:
      - 8265:8265
    environment:
      internalNode: true
      inContainer: true
      openBrowser: false
      serverURL: "${TDARR_URL}"
      nodeName: sagittarius
      priority: 0 # Highest priority
      ffmpegVersion: 7
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - "${TDARR_MOUNT_PATH}/configs:/app/configs"
      - "${TDARR_MOUNT_PATH}/server:/app/server"
      - "${MEDIA_MOUNT_PATH}:/media"
      - tdarr-cache:/temp
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: unless-stopped