name: ollama

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:0.13.5
    user: 0:0
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
        limits:
          memory: 8G
    restart: unless-stopped
    volumes:
      - /mnt/storage-pool/apps/ollama:/root/.ollama
    environment:
      OLLAMA_VULKAN: 1
      OLLAMA_HOST: 0.0.0.0:11434