services:
  postgres:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    deploy:
      resources:
        limits:
          memory: 1G
    env_file:
      - ../stack.env
    environment:
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: HDD # Sagittarius runs on HDDs, this should help optimise things a bit
    # Shared memory size, not sure why this is needed but the devs recommend this so I'm sure there's a good reason
    # See here: https://docs.docker.com/reference/compose-file/services/#shm_size
    shm_size: 128mb
    volumes:
      - ${MOUNT_BASE_PATH}/postgres:/var/lib/postgresql/data
    restart: unless-stopped