services:
  workers:
    container_name: immich-workers
    image: ghcr.io/immich-app/immich-server:v2
    environment:
      IMMICH_WORKERS_EXCLUDE: api
    env_file:
      - ../stack.env
    deploy:
      resources:
        limits:
          memory: 2G
        # Enables hardware transcoding via the dedicated GPU
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${MOUNT_BASE_PATH}/library:/data"
    restart: unless-stopped
    labels:
      prometheus.io/scrape: true
      prometheus.io/path: /metrics
      prometheus.io/port: 8082
      prometheus.io/scheme: http