services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8080:8080
    env_file:
      - stack.env
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      WEBUI_URL: "${OPENWEBUI_URL}"
      OAUTH_CLIENT_ID: "${OPENWEBUI_OIDC_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OPENWEBUI_OIDC_CLIENT_SECRET}"
      OPENID_PROVIDER_URL: "${OPENWEBUI_OIDC_PROVIDER_URL}"
      OAUTH_PROVIDER_NAME: "${OPENWEBUI_OIDC_PROVIDER_NAME}"
      OAUTH_ALLOWED_ROLES: "${OPENWEBUI_OIDC_ALLOWED_ROLES}"
      OAUTH_ADMIN_ROLES: "${OPENWEBUI_OIDC_ADMIN_ROLES}"
      OAUTH_CODE_CHALLENGE_METHOD: S256
      OAUTH_ROLES_CLAIM: groups
      OAUTH_SCOPES: openid email profile groups
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: "true"
      ENABLE_OAUTH_ROLE_MANAGEMENT: "true"
      ENABLE_OAUTH_SIGNUP: "true"
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - "${OPENWEBUI_BASE_PATH}:/app/backend/data"
    restart: unless-stopped