services:
  clamav:
    container_name: clamav
    image: clamav/clamav:latest
    user: 0:0
    env_file:
      - ../stack.env
    environment:
      CLAMD_CONF_StreamMaxLength: "${AV_MAX_SIZE}"
    deploy:
      resources:
        limits:
          memory: 4G
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    volumes:
      - /var/run/clamav:/tmp
    restart: unless-stopped