services:
  radicale:
    container_name: radicale
    image: opencloudeu/radicale:latest
    user: 568:568
    env_file:
      - ../stack.env
    deploy:
      resources:
        limits:
          memory: 200M
    volumes:
      - ../files/config:/etc/radicale/config:ro
      - ${OC_MOUNT_BASE}/radicale:/var/lib/radicale
    restart: unless-stopped