services:
  tika:
    container_name: tika
    image: apache/tika:latest
    user: 568:568
    deploy:
      resources:
        limits:
          memory: 500M
    env_file:
      - stack.env
    restart: unless-stopped